name: nlpenv
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - pip:
    - torch==1.13.0
    - torchvision==0.14.0
    - torchaudio==0.13.0
    - huggingface-hub
    - transformers
    - einops
    - accelerate
    - bitsandbytes
    - flask
    - python-dotenv
