name: nlpenv
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - colorama
  - pip:
    - torch==1.13.0
    - torchvision==0.14.0
    - torchaudio==0.13.0
    - numpy==1.26.4
    - huggingface-hub
    - evaluate
    - torchaudio
    - transformers
    - librosa
    - soundfile
    - jiwer
    - einops
    - accelerate
    - bitsandbytes
    - flask
    - python-dotenv
    - git+https://github.com/huggingface/transformers.git
    - git+https://github.com/huggingface/peft.git
    - git+https://github.com/huggingface/accelerate.git
    - datasets
    - scipy
    - ipywidgets
    - matplotlib
